-
  set:
    RelayWithBulkStore: "0x61f836ebad27a6a3cbb5c070ca6b99925eabd9a3"

-
  call:
    getBlockchainHead:
      to: $RelayWithBulkStore
      fun_name: getBlockchainHead
      sig: ''

-
  call:
    getLastBlockHeight:
      to: $RelayWithBulkStore
      fun_name: getLastBlockHeight
      sig: ''

-
  call:
    getCumulativeDifficulty:
      to: $RelayWithBulkStore
      fun_name: getCumulativeDifficulty
      sig: ''
